url = http://slingshot-dev.epssw.net:8086/solution/avanti/index.html?a=aa72bdb2-1669-4fd1-b9de-749dd0fa2eb6%27#svy_nav_fr_main
browser = chrome
Excelpath = ./src//test//java//resources//Test.xlsx
dbhost = localhost
dbport = 3306
dbuser = root
dbpassword = root123
Username = Adarsh
Password = Avanti
Owner = Avanti Computer Systems